add_includedirs("include")
target("lab4-2.mbr", function()
    add_rules("asm.bin")
    add_files("src/boot/mbr.asm")
    set_filename("mbr.bin")
end)

target("lab4-2.bootloader", function()
    add_rules("asm.bin")
    add_files("src/boot/bootloader.asm")
    set_filename("bootloader.bin")
end)

target("lab4-2.kernel", function()
    add_rules("asm.elf")
    add_files("src/boot/entry.asm", "src/kernel/*.cpp", "src/utils/*.asm")
    set_filename("kernel.bin")
    add_cxxflags("-march=i386", "-m32", "-nostdlib", "-fno-builtin", "-ffreestanding", "-fno-pic")
end)

target("lab4-2", function()
    set_kind("phony")
    add_deps("lab4-2.mbr", "lab4-2.bootloader", "lab4-2.kernel")
    add_rules("kernel.build")
end)
